import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

test('initial prototype starts with login and separates participant and operator access', async () => {
  const html = await readFile('outputs/initial-bid-prototype.html', 'utf8');

  assert.match(html, /크래프톤 입찰시스템/);
  assert.doesNotMatch(html, /<p class="eyebrow">국내용 입찰 시스템<\/p>/);
  assert.doesNotMatch(html, /<span class="status-pill live">프로토타입<\/span>/);
  assert.doesNotMatch(html, /입찰 시스템 로그인/);
  assert.match(html, /입찰 참여자 로그인/);
  assert.match(html, /data-auth-tab="login"/);
  assert.match(html, /data-auth-tab="signup"/);
  assert.match(html, /name="supplierEmail"/);
  assert.match(html, /name="supplierPassword"/);
  assert.match(html, /name="supplierSignupEmail"/);
  assert.match(html, /name="supplierSignupPassword"/);
  assert.match(html, /name="supplierSignupPasswordConfirm"/);
  assert.match(html, /placeholder="업무용 이메일"/);
  assert.match(html, /placeholder="비밀번호"/);
  assert.match(html, /비밀번호 확인/);
  assert.match(html, /가입한 로그인 정보는 14일 동안만 사용할 수 있습니다/);
  assert.match(html, /사용기간이 지나면 다시 가입해야 합니다/);
  assert.match(html, /계정 사용기간이 만료되었습니다\. 다시 가입해 주세요/);
  assert.match(html, /비밀번호가 일치하지 않습니다/);
  assert.match(html, /prototypeSupplierAccount/);
  assert.match(html, /data-action="supplier-signup"/);
  assert.match(html, /<button data-login-role="supplier">로그인<\/button>/);
  assert.match(html, /운영자 이메일/);
  assert.match(html, /name="operatorEmail"/);
  assert.match(html, /name="operatorPassword"/);
  assert.match(html, /<section class="login-card auth-login hidden" id="operatorLoginCard"/);
  assert.match(html, /<button data-login-role="operator">운영자 로그인<\/button>/);
  assert.match(html, /운영자 이메일과 비밀번호를 입력하세요/);
  assert.match(html, /function handleOperatorLogin/);
  assert.doesNotMatch(html, /auth-checklist/);
  assert.doesNotMatch(html, /이메일\/비밀번호 확인/);
  assert.doesNotMatch(html, /supplier 역할/);
  assert.doesNotMatch(html, /업체 승인 완료/);
  assert.doesNotMatch(html, /입찰 목록 보기/);
  assert.doesNotMatch(html, /공고 확인 · 제안요청서 다운로드 · 제안서 제출/);
  assert.match(html, /운영자 로그인/);
  assert.doesNotMatch(html, /공고 등록 · 평가 · Outlook 통보 문안/);
  assert.doesNotMatch(html, /공고 상태, Outlook 메일 템플릿, 평가와 결과 통보를 관리하세요/);
  assert.doesNotMatch(html, /<p class="eyebrow">플랫폼<\/p>\s*<h1>운영자 공고 관리<\/h1>/);
  assert.doesNotMatch(html, /<span class="status-pill">운영자<\/span>/);
  assert.doesNotMatch(html, /<input readonly id="inviteSubject"/);
  assert.doesNotMatch(html, /<textarea readonly id="inviteBody"/);
  assert.match(html, /시작일 \(한국시간\)/);
  assert.match(html, /종료일 \(한국시간\)/);
  assert.match(html, /제안요청서 교체/);
  assert.match(html, /입찰 참여자는 최신 제안요청서만 다운로드합니다/);
  assert.match(html, /data-save-template/);
  assert.match(html, /문안 저장/);
  assert.match(html, /수정한 내용은 문안 저장 후 복사에 반영됩니다/);
  assert.match(html, /data-login-role="supplier"/);
  assert.match(html, /data-login-role="operator"/);
  assert.doesNotMatch(html, /ALLOWED_OPERATOR_IPS/);
  assert.match(html, /function canShowOperatorLogin/);
  assert.match(html, /operator=1/);
  assert.doesNotMatch(html, /operatorHash/);
  assert.doesNotMatch(html, /window\.location\.hash/);
  assert.doesNotMatch(html, /hash\s*===\s*['"]#operator/);
  assert.match(html, /operatorLoginCard\.classList\.toggle\('hidden', !canShowOperatorLogin\(\)\)/);
  assert.match(html, /function applyOperatorAccessGate/);
  assert.doesNotMatch(html, /window\.location\.hostname/);
  assert.doesNotMatch(html, /window\.location\.protocol === 'file:'/);
  assert.doesNotMatch(html, /operatorAccessNotice/);
  assert.doesNotMatch(html, /access-note/);
  assert.doesNotMatch(html, /현재 접속 IP에서는 운영자 로그인을 표시하지 않습니다/);
  assert.match(html, /data-action="logout"/);
  assert.match(html, /id="supplierView" class="hidden"/);
  assert.match(html, /id="operatorView" class="hidden"/);
  assert.doesNotMatch(html, /<section id="supplierView" class="hidden">\s*<header class="topbar">/);
  assert.doesNotMatch(html, /<p class="eyebrow">서울공급웍스<\/p>\s*<h1>입찰 참여<\/h1>/);
  assert.doesNotMatch(html, /<span class="status-pill">공급사<\/span>/);
  assert.doesNotMatch(html, /supplierProposalCount/);
  assert.doesNotMatch(html, /<span>제출 제안서<\/span>/);
  assert.match(html, /제안서 다운로드/);
  assert.match(html, /압축 파일로 제안서 파일을 제안하세요/);
  assert.match(html, /마감 전까지 파일을 교체할 수 있습니다/);
  assert.match(html, /id="replaceProposal"/);
  assert.match(html, /파일 교체/);
  assert.doesNotMatch(html, /PDF, 문서, 압축 파일 등 제안서 파일을 선택해 제출하세요/);
  assert.match(html, /data-result-action disabled/);
  assert.match(html, /모든 제출 업체의 평가를 저장한 뒤 우선대상자를 선택할 수 있습니다/);
  assert.match(html, /결과 통보 완료 후에는 평가를 수정할 수 없습니다/);
  assert.doesNotMatch(html, /참여자 화면 원칙/);
  assert.doesNotMatch(html, /참여자는 본인이 제출한 파일 상태만 확인합니다/);
  assert.doesNotMatch(html, /평가 점수, 평가 메모, 우선대상자\/탈락자 분류는 운영자 화면에서만 확인됩니다/);
});
